name: Build, Test, Publish

on:
  workflow_dispatch:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build

      - name: Test Project
        run: dotnet test

  publish:
    needs: build-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-release: ["osx-x64", "linux-x64", "win-x64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish Artifacts
        run: |
          dotnet publish src/WebApi.csproj -r ${{ matrix.os-release }} --self-contained=true -c Release -o release/${{ matrix.os-release }} /p:PublishSingleFile=true


      - name: Copy README
        run: |
          cp ./README.md ./release/${{ matrix.os-release }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os-release }}
          path: ./release/${{ matrix.os-release }}
