name: Build and Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build

      - name: Test Project
        run: dotnet test

      - name: Publish Artifacts
        run: |
          dotnet publish src/WebApi.csproj -r osx-x64 --self-contained=true -c Release -o release/osx-x64 /p:PublishSingleFile=true
          dotnet publish src/WebApi.csproj -r linux-x64 --self-contained=true -c Release -o release/linux-x64 /p:PublishSingleFile=true
          dotnet publish src/WebApi.csproj -r win-x64 --self-contained=true -c Release -o release/win-x64 /p:PublishSingleFile=true

      - name: Copy README
        run: |
          cp ./README.md ./release/osx-x64
          cp ./README.md ./release/linux-x64
          cp ./README.md ./release/win-x64

      - name: Upload OSX Artifact
        uses: actions/upload-artifact@v3
        with:
          name: osx-x64
          path: ./release/osx-x64

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-x64
          path: ./release/linux-x64

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: win-x64
          path: ./release/win-x64
          

          